# MQJobRunner Configuration
# Environment: SIT or PREPROD
env=SIT

# ─── MQ SIT ───
mq.sit.host=192.168.100.67
mq.sit.port=1456
mq.sit.channel=NLACEQM01T.SVRCONN
mq.sit.queue.manager=NLACEQM01T
mq.sit.user=mqconn

# ─── MQ Preprod ───
mq.preprod.host=192.168.138.5
mq.preprod.port=1456
mq.preprod.channel=NLACEQM01O.SVRCONN
mq.preprod.queue.manager=NLACEQM01O
mq.preprod.user=mqclntcon

# ─── DB SIT ───
db.sit.url=jdbc:oracle:thin:@//192.168.102.37:1521/wltdbsit.neoleap.com.sa
db.sit.username=EPAY_TESTING
db.sit.password=JLSK#2936gkldw#Hjls

# ─── DB Preprod ───
db.preprod.url=jdbc:oracle:thin:@//10.10.116.85:1521/WLTPPRD
db.preprod.username=EUA_JBHASIN_C
db.preprod.password=JLSK#2936gkldw#Hjls
